apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sandeepmohapatra177/ArgoCD.git
    targetRevision: main
    path: ui_approach/nginx        # Path to nginx manifests
  destination:
    server: https://kubernetes.default.svc    # from `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
