apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-child              # Child app name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sandeepmohapatra177/ArgoCD.git # Repo containing child apps(that you have forked and cloned earlier)
    targetRevision: main
    path: ui_approach/nginx      # path of Nginx app in `argocd-demos` repo
  destination:
    server: https://172.17.0.1:33893 # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: default           # Deploys into default namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
